# Generated by Django 4.0 on 2022-02-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_article_dislikes_alter_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='looks',
            field=models.IntegerField(default=0),
        ),
    ]
