# Generated by Django 4.0 on 2022-03-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_article_looks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
