# Generated by Django 4.0 on 2022-01-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_author_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
